# Exercise 8.5.4 (fisheries)

```{r}
## Load packages
library(tidyverse)

## Load dataset
fisheries <- read_csv("https://raw.githubusercontent.com/rstudio-education/datascience-box/master/course-materials/application-exercises/ae-05-fisheries-datajoins/data/fisheries.csv")
fisheries

## Load dataset
continents <- read_csv("https://raw.githubusercontent.com/rstudio-education/datascience-box/master/course-materials/application-exercises/ae-05-fisheries-datajoins/data/continents.csv")
continents

## Statistics
fisheries %>%
  summarise(across(is.numeric, mean, na.rm = TRUE))

```


```{r}
## Task 1
fisheries <- fisheries %>% 
  print() %>% 
  left_join(continents) %>% 
  print()

fisheries %>% filter(is.na(continent))

## Or

fisheries %>% 
  anti_join(continents)

```

```{r}
## Task 2
fisheries <- fisheries %>% 
  filter(total > 100000) %>% 
  print()

```

```{r}
## Task 3
fisheries %>% 
  filter(is.na(continent))

fisheries <- fisheries %>% 
  mutate(continent = case_when(
    country == "Democratic Republic of the Congo" ~ "Africa",
    country == "Hong Kong"                        ~ "Asia",
    country == "Myanmar"                          ~ "Asia",
    TRUE                                          ~ continent
    )
  )

fisheries %>% filter(is.na(continent))

# Now there no country without a continent

```

```{r}
## Task 4
fisheries <- fisheries %>% 
  mutate(aquaculture_perc = aquaculture / total * 100) %>% 
  print()

```


```{r}
## Task 5
fisheries %>% 
  group_by(continent) %>% 
  summarise(mean_ap = mean(aquaculture_perc))

```


```{r}
## Task 6
fisheries_summary_continent <- fisheries %>% 
  group_by(continent) %>% 
  summarise(mean_ap = mean(aquaculture_perc),
            min_ap = min(aquaculture_perc),
            max_ap = max(aquaculture_perc)) %>% 
  print()

```

```{r}
## Task 7
fisheries_summary_continent %>% 
  arrange(desc(mean_ap))

```

```{r}
## Task 8
fisheries_summary_continent %>% 
  ggplot(aes(mean_ap, reorder(continent, mean_ap))) +
  geom_col() +
  labs(
    x = "",
    y = "",
    title = "Average share of aquaculture by continent",
    subtitle = "out of total fisheries harvest",
    caption = "Source: bit.ly/2VrawTt"
  )

```
