# Exercise 9.7.2

```{r}
## Load packages
library(tidyverse)
library(tfa)
library(skimr)

## Check data
glimpse(profit)
skim (profit)

```


```{r}
## Task 1

# a)
profit <- profit %>% 
  mutate(across(where(is.character), as.factor))

# b)
profit %>% 
  group_by(Product.Line) %>%
  summarise(Profit = sum(Profit)) %>%
  ggplot(aes(Product.Line, Profit)) +
  geom_col()
  
# c)
profit %>% 
  group_by(Product.Line) %>%
  summarise(Profit = sum(Profit)) %>%
  ggplot(aes(reorder(Product.Line, Profit), Profit))+
  geom_col()

# d)
profit %>% 
  group_by(Product.Line) %>%
  summarise(Profit = sum(Profit)) %>%
  ggplot(aes(reorder(Product.Line, Profit), Profit))+
  geom_col() + 
  labs(title = "Total profitability of the product lines")

# e)
profit %>% 
  group_by(Product.Line) %>%
  summarise(Profit = sum(Profit)) %>%
  ggplot(aes(reorder(Product.Line, Profit), Profit))+
  geom_col() + 
  labs(title = "Total profit for each product lines") + 
  xlab("Product line") + 
  theme(axis.text.x = element_text(angle = 90))

# f)
dat <- profit %>% 
  group_by(Product.Line) %>% 
  summarise(Profit = sum (Profit))

# Worst
dat %>% 
  slice_min(Profit)

# Best
dat %>% 
  slice_max(Profit)

```

```{r}
## Task 2
profit %>% 
  group_by(Product.Line, Quarter) %>%
  summarise(Profit = sum(Profit)) %>%
  ggplot(aes(reorder(Product.Line, Profit), Profit))+
  geom_col() + 
  facet_grid(cols = vars(Quarter)) +
  labs(title = "Total profit for each product lines") + 
  xlab("Product line") + 
  theme(axis.text.x = element_text(angle = 90))

```


```{r}
## Task 3
profit %>% 
  ggplot(aes(Product.Line, Profit))+
  geom_boxplot() +
  labs(title = "Total profit for each product lines") +
  theme(axis.text.x = element_text(angle = 90))

```

```{r}
## Task 4
profit %>% 
  group_by(Customer.ID) %>%
  summarise(Profit = sum(Profit)) %>%
  ggplot(aes(reorder(Customer.ID, Profit), Profit)) +
  geom_col() + 
  labs(title = "Total profit for each customer") + 
  xlab("Customers") + 
  theme(axis.text.x = element_text(angle = 90))

```

```{r}
## Task 5
profit %>% 
  group_by(Customer.ID) %>%
  summarise(AVGProfit = mean(Profit)) %>%
  ggplot(aes(reorder(Customer.ID, AVGProfit), AVGProfit)) +
  geom_col() + 
  labs(title = "Mean profit for each customer") + 
  xlab("Customers") + 
  theme(axis.text.x = element_text(angle = 90))

```

```{r}
## Task 6
profit %>% 
  group_by(Customer.ID) %>%
  summarise(ctr = n(), TotalProfit = sum(Profit)) %>%
  ggplot(aes(reorder(Customer.ID, TotalProfit), ctr, fill = TotalProfit)) +
  geom_col() + 
  labs(title = "Number of transactions for each customer") + 
  xlab("Customer") + ylab("Transactions") +
  theme(axis.text.x = element_text(angle = 90))

```

```{r}
## Task 7
profit %>% 
  ggplot(aes(Customer.ID, Profit))+
  geom_boxplot() +
  labs(title = "Total profit for each customer") +
  theme(axis.text.x = element_text(angle = 90))

```