# Exercise 8.5.2

```{r}
## Install package
install.packages("babynames")
install.packages("skimr")

```

```{r}
## Load packages
library(tidyverse)
library(babynames)
library(skimr)
```

```{r}
## Use skim to check babynames
skim(babynames)

# Task 1
## 1. select(babynames, -c(year, sex, prop))
## 2. select(babynames, name:n)
## 3. select(babynames, starts_with("n"))
## 4. select(babynames, ends_with("n"))

## Answer: 4

```

```{r}
# Task 2
## a)
babynames %>%
  filter(prop >= 0.08)

## b)
babynames %>% 
  filter(name == "Sea")

```

```{r}
# Task 3
# a)
babynames %>% 
  filter(name == "Sue", sex == "M")

# b)
babynames %>% 
  filter(year == 1880, n == "5" | n == "6")

# c)
babynames %>%
  filter(name %in% c("Acura", "Lexus","Yugo"))

```

```{r}
# Task 4
babynames %>%
  summarize(min(n), max(n))

```

```{r}
# Task 5
babynames %>% 
  filter(year == 2017, sex == "F") %>% 
  select(name, n) %>% 
  arrange(desc(n))

```

```{r}
# Task 6
babynames %>%
  filter(name == "Mikkel", sex == "M")

```

```{r}
# Task 7
babynames %>%
  filter(name == "Khaleesi") %>% 
  summarize(total = sum(n), first = min(year))

```

```{r}
# Task 8
babynames %>% 
  group_by(name, sex) %>%
  summarize(total = sum(n)) %>%
  arrange(desc(total))
  
```

```{r}
# Task 9
babynames %>%
  group_by(year) %>% 
  summarize(total=sum(n))

```

```{r}
# Task 10
babynames %>%
  group_by(year, sex) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  arrange(year, sex, desc(prop))

```

```{r}
# Task 11
babynames %>% 
  group_by(year, sex) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(year > 2009, rank == 1)

```
