## Exercise 8.5.1

```{r}
# Install package
install.packages("gapminder")

```

```{r}
# Load package
library(gapminder)
library(tidyverse)

```

```{r}
# Task 1
gapminder %>% 
  glimpse()

gapminder %>% 
  summary()

gapminder %>% 
  head()

gapminder %>% 
  tail()

```

```{r}
# Task 2

## a) Count number of countries
gapminder %>%
  count(country) %>% 
  nrow()

## b) Count number of continents
gapminder %>%
  count(continent) %>% 
  nrow()

## c) Count number of countries pr. continent
gapminder %>%
  count(country, continent) %>% 
  count(continent)

  #or

## c) Count number of countries pr. continent  
gapminder %>%
  distinct(country, continent) %>% 
  count(continent)

```

```{r}
# Task 3  

## Retrieve a vector with all distinct continent values.
gapminder %>% 
  distinct(continent) %>% 
  pull(continent) %>% 
  as.character()

```

```{r}
# Task 4

# a)
gapminder %>% 
  filter(lifeExp < 29)

# b)
gapminder %>% 
  filter(country == "Rwanda", year > 1979)

# c)
gapminder %>% 
  filter(country %in% c("Rwanda","Afghanistan","France"))

```

```{r}
# Task 5

## a)
gapminder %>% 
  select(year, lifeExp)

## b)
gapminder %>% 
  select(country, gdpPercap)

```

```{r}
# Task 6
gapminder %>% 
  filter(gdpPercap > 40000 & continent == "Europe" |gdpPercap < 500 & continent == "Africa") %>% 
  select(continent, country, gdpPercap)

```

```{r}

# Task 7
gapminder %>% 
  mutate(gdp = pop * gdpPercap)

```

```{r}
# Task 8
mean_dk <- gapminder %>% 
  filter(country == "Denmark") %>% 
  pull(gdpPercap) %>% 
  mean() %>% 
  print()

dat <- gapminder %>% 
  mutate(gdpPercapRel = gdpPercap / mean_dk) %>% 
  print()

```

```{r}
# Task 9

## a)
gapminder %>% 
  arrange(year, country)


## b)
gapminder %>% 
  filter(year == 2007) %>% 
  arrange(lifeExp)

## c)
gapminder %>% 
  filter(year == 2007) %>% 
  arrange(desc(lifeExp))

```

```{r}
# Task 10

## a)
gapminder %>% 
  select(everything(), yr = year)

## b)
gapminder %>% 
  select(-pop)
  
## c)
gapminder %>% 
  select(year, pop, everything())

```

```{r}
# Task 11

## a)
gapminder %>% 
  group_by(continent) %>% 
  summarize(n = n())

  # or

gapminder %>% 
  group_by(continent) %>% 
  count()

## b)
gapminder %>%
  group_by(continent) %>% 
  summarize(n = n(),n_countries = n_distinct(country))


## c)
gapminder %>%
  group_by(continent) %>% 
  summarize(avg_lifeExp = mean(lifeExp))


## d)
gapminder %>%
  filter(continent == "Asia") %>% 
  group_by(year) %>% 
  summarize(min_lifeExp = min(lifeExp),max_lifeExp = max(lifeExp))

```

```{r}
# Task 12
gapminder %>% 
  
  ## Group by country
  group_by(country) %>% 
  
  ## Select relevant columns
  select(country, year, lifeExp) %>% 
  
  ## Make sure that the data is sorted correct
  arrange(year, .by_group = TRUE) %>% 
  
  ## Define new variable
  mutate(lifeExp_gain = lifeExp - first(lifeExp)) %>% 
  
  ## Filter (nice for printing)
  filter(year < 1963)

```

```{r}
# Task 13
gapminder %>%
  
  ## Select relevant columns
  select(country, year, continent, lifeExp) %>%
  
  ## Group
  group_by(continent, country) %>%
  
  ## Within country
  mutate(le_delta = lifeExp - lag(lifeExp)) %>%
  
  ## Find lowest value
  summarize(worst_le_delta = min(le_delta, na.rm = TRUE)) %>%
  
  ## Find min in each continent
  slice_min(worst_le_delta) %>%
  
  ## Arrange
  arrange(worst_le_delta) 

```
