```{r}
# Task 1

## Set file location
url <- "https://api.statbank.dk/v1/data/FLYV41/CSV?lang=en&LUFTHAVN=*&Tid=*&Transport=*"

## Load Package
library(readr)

## Read format of file
cat(read_lines(url, n_max = 3), sep = "\n")

```


```{r}
# Task 2

## Use csv2 as it is a Semi-colon delimited file
read_csv2(url)

```

```{r}
# Task 3

## Read package
library(jsonlite)

## Set file location
url <- "https://api.statbank.dk/v1/tableinfo/FLYV41?lang=en"

## Make a list
lst <- read_json(url, simplifyVector = T)

## View list
View(lst)

## Note the data returned is in json format, so we use read_json to read the data into a list.

```

```{r}
# Task 4

library(tidyverse)

info <- function(tab_id){
  url <- str_c("https://api.statbank.dk/v1/tableinfo/", tab_id, "?lang=en")
  lst <- read_json(url, simplifyVector = T)
  return(list(description = lst$description, unit = lst$unit, variables = lst$variables))
}

info("FLYV41")

```

```{r}
# Task 5

## Information about all the data sets can be retrieved using:

url <- "https://api.statbank.dk/v1/tables?lang=en"
lst <- jsonlite::read_json(url, simplifyVector = T)
View(lst)

## Have a look at the row for FLYV41

```

```{r}
# Task 6

## Given the information about variables in a data set we can construct the url to retrieve the data in csv format:

tab_id <- "FLYV41"
url <- str_c("https://api.statbank.dk/v1/tableinfo/", tab_id, "?lang=en")
lst <- read_json(url, simplifyVector = T) 
col_id <- c(1,3)  # column ids in lst$variables$id
cols <- lst$variables$id[col_id]
url <- str_c("https://api.statbank.dk/v1/data/", tab_id, "/CSV?lang=en&", str_c(cols, collapse = "=*&"), "=*") %>% URLencode()
url

get_data <- function(tab_id, col_id = NULL) {
   url <- str_c("https://api.statbank.dk/v1/tableinfo/", tab_id, "?lang=en")
   lst <- read_json(url, simplifyVector = T) 
   cols <- lst$variables$id
   if (!is.null(col_id)) cols <- cols[col_id]
   url <- str_c("https://api.statbank.dk/v1/data/", tab_id, "/CSV?lang=en&",
   str_c(cols, collapse = "=*&"), "=*") %>% URLencode()
   dat <- read_csv2(url)
   return(dat)
}

get_data("FLYV41", 3)
get_data("FLYV41", 1:2)
get_data("FLYV41")

```

```{r}
# Task 7

dat <- get_data("FOLK1A", c(2,3,5))
csv_file <- "testing.csv"
write_csv(dat, path = csv_file)

```

```{r}
# Task 8


## Save to Excel

### Install Package
install.packages("openxlsx")

### Read Package
library(openxlsx)

### Write to Excel
write.xlsx(dat, "test1.xlsx", sheetName="FOLK1A")


## Save to Google Sheets

### Install package
install.packages("googlesheets4")

### Read package
library(googlesheets4)

### Write to Google Sheet
gs4_auth()
gs <- gs4_create("test")
write_sheet(dat, ss = gs, sheet = "FOLK1A")
gs4_browse(gs)

```

